#! /bin/sh
FONT_FAMILY='-*-terminus-bold-*-*-*-14-*-*-*-*-*-*-*'
FONT_SIZE=16
export PANEL_HEIGHT=16

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config -m ^1 top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %b %e %Y %r' > "$PANEL_FIFO" &
fetch_weather > "$PANEL_FIFO" &
fetch_sne_stock > "$PANEL_FIFO" &

case "$flavor" in
	bar)
		cat "$PANEL_FIFO" | panel_bar | bar -f "$FONT_FAMILY" -g 1920x16+0+0 &
		;;
	dzen2)
		. panel_colors
		cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
		;;
esac

wait
