#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="${line#?}"
			;;
		T*)
			# xtitle output
			title="%{F#00FFFF}${line#?}%{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					O*)
						# focused occupied desktop
						wm_infos="$wm_infos %{F#AA0000}${name}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="$wm_infos ${name}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="$wm_infos ${name}"
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos ${name}"
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos ${name}"
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos ${name}"
						;;
					L*)
						# layout
						layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
						wm_infos="$wm_infos   %{Fgreen}$layout%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}$wm_infos %{c}$title %{r}$sys_infos"
done
