#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config split_ratio         0.52
bspc config focus_follows_pointer true
bspc config top_padding 20
bspc config window_gap 0


bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on

sxhkd &
export PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=24
export PATH=$PATH:/home/ramin/.config/panel/
panel &

