#! /bin/sh

bspc monitor DVI-I-1 -d A B C
bspc monitor DVI-D-0 -d 1 2 3

bspc config border_width        2
bspc config split_ratio         0.52
bspc config focus_follows_pointer true
bspc config window_gap 0
bspc config wm_name LG3D

#bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Gimp follow=on floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on

sxhkd &
export PANEL_FIFO=/tmp/panel-fifo
export PATH=$PATH:/home/ramin/.config/panel/
bspc monitor -f primary 
panel &
